### ISSUE TITLE
Hacks

### ISSUE THREAD

**Issue by Hamster1boss** [XPH4N70M/WA_CRASHER#17]

**Comment by monsieurcharo192-glitch** [comment]
Du hast die Wahl getroffen, weil ich nicht neidisch darauf war, die Videos von ihr zu verkaufen, oder du lagst mit den Minen auf einem Video oder deinem gewalttätigen Baby, das du dir vorstellst, als du dich im Gefängnis versteckst. Du bist unbesiegbar und hast dich bei Whatsapp gemeldet, um das Verbot einer bestimmten Nummer zu erhalten.


E não é só isso, senhor, ele gosta de enganar as pessoas se passando por mim e aplicando golpes. O senhor não tem vergonha? Acha que o WhatsApp vai te espionar? Sem fazer nada, vou denunciá-lo e o WhatsApp banirá seu número permanentemente. O senhor dorme com menores, mente se passando por mim, o que me causa problemas, rouba dinheiro de pessoas que confiam em você e, acima de tudo, estuprou um bebê, ele tinha uns 2 anos, o que está acontecendo com o senhor?


Je vërtet i pashpresë. Shpresoj të vdesësh në burg. Guxove të vidhje identitetin tim, të flije me të mitur, të rishitësh videot e tyre në WhatsApp dhe të flije me një foshnjë. Si guxon? Do ta vendos numrin tënd këtu që WhatsApp të mund të të identifikojë, o i shkretë i ndyrë.


=+237695768250
